# This file is generated by Anlogic Timing Wizard. 08 11 2020

#Created Clock
create_clock -name clk_24m -period 41.666 -waveform {0 20.833} [get_ports {clk_24m}]
create_clock -name pclk -period 41.666 -waveform {0 20.833} [get_ports {cam_pclk}] -add

#Derive PLL Clocks
derive_pll_clocks -gen_basic_clock

